name: NowTV VOD Scraper

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # <-- Takılmayı önler

    permissions:
      contents: write

    steps:
      - name: Repoyu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install cloudscraper beautifulsoup4

      - name: Scraper'ı Çalıştır
        run: python nowtv.py

      - name: Git Yapılandırması
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "GitHub Actions"

      - name: Commit ve Push
        run: |
          git add nowtv.m3u
          # Hata vermesin diye kontrol ekledik
          git diff --staged --quiet || git commit -m "NOW TV Güncellemesi"
          
          # Çakışma önleyici pull
          git pull --rebase origin main || true
          git push origin main
